### ISSUE TITLE
问题详情页

### ISSUE THREAD

**Issue by binnng** [binnng/mifan#8]
![image](https://cloud.githubusercontent.com/assets/2696107/3710222/119e882a-147b-11e4-874d-2dd945fe2c7c.png)

每个问题的详情页

列出针对这个问题的每个回答，回答包括：
- 回答者信息
- 喜欢信息
- 评论数目

**Comment by actors315** [comment]
需要分页么？？

**Comment by binnng** [comment]
不需要。后期可能需要，所以要考虑分页：）
